export const ERROR_CODES = {
  internalError: 'INTERNAL_ERROR',
  validationError: 'VALIDATION_ERROR',
  unauthorized: 'UNAUTHORIZED',
  forbidden: 'FORBIDDEN',
  authUnavailable: 'AUTH_UNAVAILABLE',
  opdUnavailable: 'OPD_UNAVAILABLE',
  departmentNotFound: 'DEPARTMENT_NOT_FOUND',
  departmentNameConflict: 'DEPARTMENT_NAME_CONFLICT',
  patientNotFound: 'PATIENT_NOT_FOUND',
  doctorNotFound: 'DOCTOR_NOT_FOUND',
  doctorAssignmentTargetNotDoctor: 'DOCTOR_ASSIGNMENT_TARGET_NOT_DOCTOR',
  appointmentNotFound: 'APPOINTMENT_NOT_FOUND',
  appointmentVersionConflict: 'APPOINTMENT_VERSION_CONFLICT',
  appointmentInvalidStatusTransition: 'APPOINTMENT_INVALID_STATUS_TRANSITION',
  schedulingTargetNotDoctor: 'SCHEDULING_TARGET_NOT_DOCTOR',
} as const;
